#!/bin/bash

if [ -z ${RPI_USER+x} ]; then 
    RPI_USER=pi
fi

if [ -z ${RPI_HOST+x} ]; then 
    RPI_HOST=raspberry.local
fi

if [ -z ${RPI_UUID+x} ]; then 
    RPI_UUID=$(uuidgen)
fi

if [ -z ${SERVICE_NAME+x} ]; then 
    SERVICE_NAME=rpi-builder
fi


function gvm:install {
    echo "go version should be go1.11"
    echo ""
    echo "run following commands"
    echo "gvm pkgset create go-rpi-builder"
    echo "gvm pkgset use go-rpi-builder"
    echo "go mod download"
}

function mac:build {
    mkdir -p ./bin/darwin
    echo "building rpi-agent..."
    go build -o ./bin/darwin/rpi-agent main.go
}

function rpi:build {
    mkdir -p ./bin/arm
    echo "building rpi-agent..."
    env GOOS=linux GOARCH=arm GOARM=5 go build -o ./bin/arm/rpi-agent main.go
}

function rpi:mv {
    echo "update agent..."
    echo "stop rpi-agent service"
    
    local user=${1:-$RPI_USER}
    local host=${2:-$RPI_HOST}

    local certs="-i $dir/ops/certs/dkit_rsa"

    ssh $certs $user@$host -C "sudo systemctl stop rpi-agent.service"

    #TODO: we prob want to give it a random name to prevent clashes
    echo "move agent tmp directory..."
    scp $certs ./bin/arm/rpi-agent $user@$host:/tmp/rpi-agent
    
    echo "move agent to final destination directory..."
    ssh $certs $user@$host -C "sudo mv /tmp/rpi-agent /usr/local/bin/rpi-agent"

    echo "start rpi-agent service"
    ssh $certs $user@$host -C "sudo systemctl start rpi-agent.service"
}

function release:build {
    mkdir -p ./bin/arm
    
    VERSION=${1:-0.0.1}
    BUILD_DATE=`date -u +%Y%m%d.%H%M%S`
    
    echo "go build ldflags -X main.VERSION=$VERSION -X main.BUILD_DATE=$BUILD_DATE"
    env GOOS=linux GOARCH=arm GOARM=5 go build -ldflags "-X main.VERSION=$VERSION -X main.BUILD_DATE=$BUILD_DATE" -o ./bin/arm/rpi-agent main.go
}

function release:update {
    echo "release upddate..."
    local user=${1:-$RPI_USER}
    local host=${2:-$RPI_HOST}
    local tag=${3:-0.0.1}

    release:build $tag 
    rpi:mv $user $host
    test:service $host
}

# install binary and service on host machine
# We can pass an env file with values that will
# be available for the running service.
# 
# @arg 1 {string} [user=pi] Username
# @arg 2 {string} [host=raspberry] Hostname
# @arg 3 {string} envfile Env file used for service
# @arg 4 {string} [tag=0.0.1]
function service:install {

    local user=${1:-$RPI_USER}
    local host=${2:-$RPI_HOST}
    local envfile=$3
    # local uuid=${3:-$RPI_UUID}
    local tag=${4:-0.0.1}

    local dir
    dir=$(pwd)

    local certs="-i $dir/ops/certs/dkit_rsa"

    release:build $tag

    rpi:mv $user $host

    if [ -z "$envfile" ]; then
        echo "we are using default env configuration for device..."
    else
        ssh "$certs" "$user@$host" -C "sudo -u$user mkdir -p /tmp/service/opt/$SERVICE_NAME/"
        scp "$certs" "$envfile" "$user@$host":/tmp/service/opt/$SERVICE_NAME/$SERVICE_NAME.env 
    fiq
    
    ssh "$certs" "$user@$host" 'bash -s' < "$dir/$script"

    test:service $host
}

# update binary and service on host machine
# @arg 1 {string} [user=pi] Username
# @arg 2 {string} [host=raspberry] Hostname
# @arg 3 {string} envfile Env file used for service
# @arg 4 {string} tag If present triggers binary build
function service:update {
    
    local user=${1:-$RPI_USER}
    local host=${2:-$RPI_HOST}
    local envfile=$3
    local script="ops/scripts/uninstaller"

    local dir
    dir=$(pwd)

    local certs="-i $dir/ops/certs/dkit_rsa"

    # if [ -z ${envfile+x} ]; then 
    if [ -z "$envfile" ]; then
        echo "use default env configuration for device $user@$host"
    else
        scp "$certs" "$envfile" "$user@$host":/opt/$SERVICE_NAME/$SERVICE_NAME.env 
    fi

    if [ -z "$4" ]; then
        release:build $4
    fi

    rpi:mv "$user" "$host"
}

# uninstall binary and service on host machine
# @arg 1 {string} [user=pi]
# @arg 2 {string} [host=raspberry]
function service:uninstall {
    local user=${1:-$RPI_USER}
    local host=${2:-$RPI_HOST}
    local script="ops/scripts/uninstaller"

    local dir
    dir=$(pwd)

    local certs="-i $dir/ops/certs/dkit_rsa"

    ssh "$certs" "$user@$host" 'bash -s' < "$dir/$script"
}

function test:service {
    local host=${1:-$RPI_HOST}
    curl -s $host:8080 | jq
}

function version:bump {
    echo "TODO :)"
    # https://stackoverflow.com/questions/4485399/how-can-i-bump-a-version-number-using-bash
    # https://gist.github.com/andyexeter/da932c9644d832e3be6706d20d539ff7
}

function help {
    echo "run <task> <args>"
    echo "Tasks:"
    compgen -A function | grep -v '^_' | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}

