#!/bin/bash
set -ex

SERVICE_NAME=rpi-agent

tmpdir=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")

sed "s/User=pi/User=$USER/g" "/tmp/service/etc/systemd/system/$SERVICE_NAME.service" > "$tmpdir/$SERVICE_NAME.service"

sudo mkdir -p /opt/$SERVICE_NAME/scripts
sudo cp /tmp/service/opt/$SERVICE_NAME/$SERVICE_NAME.env /opt/$SERVICE_NAME/$SERVICE_NAME.env

sudo chown -R "$USER" /opt/$SERVICE_NAME

sudo cp "$tmpdir/$SERVICE_NAME.service" /etc/systemd/system/$SERVICE_NAME.service
sudo chmod 644 /etc/systemd/system/$SERVICE_NAME.service

sudo cp /tmp/service/etc/rsyslog.d/$SERVICE_NAME.conf  /etc/rsyslog.d/$SERVICE_NAME.conf

sudo cp /tmp/service/etc/logrotate.d/$SERVICE_NAME.conf /etc/logrotate.d/$SERVICE_NAME.conf

########## We should get rid of this and just the flag in the start cmd
sudo mkdir -p /usr/local/src/$SERVICE_NAME/metadata
sudo chown -R $USER /usr/local/src/$SERVICE_NAME/
METADATA="/usr/local/src/$SERVICE_NAME/metadata/.device_uuid"
if [ ! -e $METADATA ]; then echo $(cat /proc/sys/kernel/random/uuid) > ${METADATA}; fi

########## 


sudo mkdir /var/log/$SERVICE_NAME
sudo touch /var/log/$SERVICE_NAME/$SERVICE_NAME.log
sudo chown -R root:adm /var/log/$SERVICE_NAME

sudo systemctl daemon-reload
sudo systemctl restart rsyslog
sudo systemctl enable "$SERVICE_NAME.service"